locals {
  global_settings = flatten([
    for device in local.devices : [
      try(local.device_config[device.name].global_settings, null) != null ? {
        key                                    = device.name
        nso_instance                           = device.name
        connect_timeout                        = try(local.device_config[device.name].global_settings.connect_timeout, local.defaults.nso.devices.configuration.global_settings.connect_timeout, null)
        read_timeout                           = try(local.device_config[device.name].global_settings.read_timeout, local.defaults.nso.devices.configuration.global_settings.read_timeout, null)
        write_timeout                          = try(local.device_config[device.name].global_settings.write_timeout, local.defaults.nso.devices.configuration.global_settings.write_timeout, null)
        no_wait_for_lock                       = try(local.device_config[device.name].global_settings.no_wait_for_lock, local.defaults.nso.devices.configuration.global_settings.no_wait_for_lock, null)
        wait_for_lock_timeout                  = try(local.device_config[device.name].global_settings.wait_for_lock_timeout, local.defaults.nso.devices.configuration.global_settings.wait_for_lock_timeout, null)
        wait_for_lock_infinity                 = try(local.device_config[device.name].global_settings.wait_for_lock_infinity, local.defaults.nso.devices.configuration.global_settings.wait_for_lock_infinity, null)
        ssh_keep_alive_interval                = try(local.device_config[device.name].global_settings.ssh_keep_alive_interval, local.defaults.nso.devices.configuration.global_settings.ssh_keep_alive_interval, null)
        ssh_keep_alive_count                   = try(local.device_config[device.name].global_settings.ssh_keep_alive_count, local.defaults.nso.devices.configuration.global_settings.ssh_keep_alive_count, null)
        ssh_algorithms_public_key              = try(local.device_config[device.name].global_settings.ssh_algorithms_public_key, local.defaults.nso.devices.configuration.global_settings.ssh_algorithms_public_key, null)
        ssh_algorithms_kex                     = try(local.device_config[device.name].global_settings.ssh_algorithms_kex, local.defaults.nso.devices.configuration.global_settings.ssh_algorithms_kex, null)
        ssh_algorithms_mac                     = try(local.device_config[device.name].global_settings.ssh_algorithms_mac, local.defaults.nso.devices.configuration.global_settings.ssh_algorithms_mac, null)
        ssh_algorithms_cipher                  = try(local.device_config[device.name].global_settings.ssh_algorithms_cipher, local.defaults.nso.devices.configuration.global_settings.ssh_algorithms_cipher, null)
        ssh_algorithms_compression             = try(local.device_config[device.name].global_settings.ssh_algorithms_compression, local.defaults.nso.devices.configuration.global_settings.ssh_algorithms_compression, null)
        ssh_algorithms_dh_group_min_size       = try(local.device_config[device.name].global_settings.ssh_algorithms_dh_group_min_size, local.defaults.nso.devices.configuration.global_settings.ssh_algorithms_dh_group_min_size, null)
        ssh_algorithms_dh_group_preferred_size = try(local.device_config[device.name].global_settings.ssh_algorithms_dh_group_preferred_size, local.defaults.nso.devices.configuration.global_settings.ssh_algorithms_dh_group_preferred_size, null)
        ssh_algorithms_dh_group_max_size       = try(local.device_config[device.name].global_settings.ssh_algorithms_dh_group_max_size, local.defaults.nso.devices.configuration.global_settings.ssh_algorithms_dh_group_max_size, null)
        ned_keep_alive_interval                = try(local.device_config[device.name].global_settings.ned_keep_alive_interval, local.defaults.nso.devices.configuration.global_settings.ned_keep_alive_interval, null)
        ned_keep_alive_count                   = try(local.device_config[device.name].global_settings.ned_keep_alive_count, local.defaults.nso.devices.configuration.global_settings.ned_keep_alive_count, null)
        connect_retries_attempts               = try(local.device_config[device.name].global_settings.connect_retries_attempts, local.defaults.nso.devices.configuration.global_settings.connect_retries_attempts, null)
        connect_retries_timeout                = try(local.device_config[device.name].global_settings.connect_retries_timeout, local.defaults.nso.devices.configuration.global_settings.connect_retries_timeout, null)
        trace                                  = try(local.device_config[device.name].global_settings.trace, local.defaults.nso.devices.configuration.global_settings.trace, null)
        trace_output                           = try(local.device_config[device.name].global_settings.trace_output, local.defaults.nso.devices.configuration.global_settings.trace_output, null)
        ned_settings_use_confirmed_commit      = try(local.device_config[device.name].global_settings.ned_settings_use_confirmed_commit, local.defaults.nso.devices.configuration.global_settings.ned_settings_use_confirmed_commit, null)
        ned_settings_use_validate              = try(local.device_config[device.name].global_settings.ned_settings_use_validate, local.defaults.nso.devices.configuration.global_settings.ned_settings_use_validate, null)
        ned_settings_use_startup               = try(local.device_config[device.name].global_settings.ned_settings_use_startup, local.defaults.nso.devices.configuration.global_settings.ned_settings_use_startup, null)
        ned_settings_use_transaction_id        = try(local.device_config[device.name].global_settings.ned_settings_use_transaction_id, local.defaults.nso.devices.configuration.global_settings.ned_settings_use_transaction_id, null)
        ned_settings_use_private_candidate     = try(local.device_config[device.name].global_settings.ned_settings_use_private_candidate, local.defaults.nso.devices.configuration.global_settings.ned_settings_use_private_candidate, null)
        ned_settings_use_junos_rollback        = try(local.device_config[device.name].global_settings.ned_settings_use_junos_rollback, local.defaults.nso.devices.configuration.global_settings.ned_settings_use_junos_rollback, null)
        no_overwrite_enabled_by_default        = try(local.device_config[device.name].global_settings.no_overwrite_enabled_by_default, local.defaults.nso.devices.configuration.global_settings.no_overwrite_enabled_by_default, null)
        no_overwrite_compare                   = try(local.device_config[device.name].global_settings.no_overwrite_compare, local.defaults.nso.devices.configuration.global_settings.no_overwrite_compare, null)
        lsa_no_overwrite_enabled_by_default    = try(local.device_config[device.name].global_settings.lsa_no_overwrite_enabled_by_default, local.defaults.nso.devices.configuration.global_settings.lsa_no_overwrite_enabled_by_default, null)
        lsa_no_overwrite_compare               = try(local.device_config[device.name].global_settings.lsa_no_overwrite_compare, local.defaults.nso.devices.configuration.global_settings.lsa_no_overwrite_compare, null)
        out_of_sync_commit_behaviour           = try(local.device_config[device.name].global_settings.out_of_sync_commit_behaviour, local.defaults.nso.devices.configuration.global_settings.out_of_sync_commit_behaviour, null)
        use_lsa                                = try(local.device_config[device.name].global_settings.use_lsa, local.defaults.nso.devices.configuration.global_settings.use_lsa, null)
        no_lsa                                 = try(local.device_config[device.name].global_settings.no_lsa, local.defaults.nso.devices.configuration.global_settings.no_lsa, null)
        session_limits_max_sessions            = try(local.device_config[device.name].global_settings.session_limits_max_sessions, local.defaults.nso.devices.configuration.global_settings.session_limits_max_sessions, null)
        session_limits_connect_rate_burst      = try(local.device_config[device.name].global_settings.session_limits_connect_rate_burst, local.defaults.nso.devices.configuration.global_settings.session_limits_connect_rate_burst, null)
        session_limits_max_wait_time           = try(local.device_config[device.name].global_settings.session_limits_max_wait_time, local.defaults.nso.devices.configuration.global_settings.session_limits_max_wait_time, null)
        session_pool_max_sessions              = try(local.device_config[device.name].global_settings.session_pool_max_sessions, local.defaults.nso.devices.configuration.global_settings.session_pool_max_sessions, null)
        session_pool_idle_time                 = try(local.device_config[device.name].global_settings.session_pool_idle_time, local.defaults.nso.devices.configuration.global_settings.session_pool_idle_time, null)
        session_pool_pool_max_sessions         = try(local.device_config[device.name].global_settings.session_pool_pool_max_sessions, local.defaults.nso.devices.configuration.global_settings.session_pool_pool_max_sessions, null)
        commit_queue_enabled_by_default        = try(local.device_config[device.name].global_settings.commit_queue_enabled_by_default, local.defaults.nso.devices.configuration.global_settings.commit_queue_enabled_by_default, null)
        commit_queue_atomic                    = try(local.device_config[device.name].global_settings.commit_queue_atomic, local.defaults.nso.devices.configuration.global_settings.commit_queue_atomic, null)
        commit_queue_retry_attempts            = try(local.device_config[device.name].global_settings.commit_queue_retry_attempts, local.defaults.nso.devices.configuration.global_settings.commit_queue_retry_attempts, null)
        commit_queue_retry_timeout             = try(local.device_config[device.name].global_settings.commit_queue_retry_timeout, local.defaults.nso.devices.configuration.global_settings.commit_queue_retry_timeout, null)
        commit_queue_error_option              = try(local.device_config[device.name].global_settings.commit_queue_error_option, local.defaults.nso.devices.configuration.global_settings.commit_queue_error_option, null)
        commit_retries_attempts                = try(local.device_config[device.name].global_settings.commit_retries_attempts, local.defaults.nso.devices.configuration.global_settings.commit_retries_attempts, null)
        commit_retries_timeout                 = try(local.device_config[device.name].global_settings.commit_retries_timeout, local.defaults.nso.devices.configuration.global_settings.commit_retries_timeout, null)
        trace_dir                              = try(local.device_config[device.name].global_settings.trace_dir, local.defaults.nso.devices.configuration.global_settings.trace_dir, null)
        report_multiple_errors                 = try(local.device_config[device.name].global_settings.report_multiple_errors, local.defaults.nso.devices.configuration.global_settings.report_multiple_errors, null)
      } : null
    ] if try(local.device_config[device.name].global_settings, null) != null
  ])
}

resource "nso_global_settings" "global_settings" {
  for_each                               = { for gs in local.global_settings : gs.key => gs }
  instance                               = each.value.nso_instance
  connect_timeout                        = each.value.connect_timeout
  read_timeout                           = each.value.read_timeout
  write_timeout                          = each.value.write_timeout
  no_wait_for_lock                       = each.value.no_wait_for_lock
  wait_for_lock_timeout                  = each.value.wait_for_lock_timeout
  wait_for_lock_infinity                 = each.value.wait_for_lock_infinity
  ssh_keep_alive_interval                = each.value.ssh_keep_alive_interval
  ssh_keep_alive_count                   = each.value.ssh_keep_alive_count
  ssh_algorithms_public_key              = each.value.ssh_algorithms_public_key
  ssh_algorithms_kex                     = each.value.ssh_algorithms_kex
  ssh_algorithms_mac                     = each.value.ssh_algorithms_mac
  ssh_algorithms_cipher                  = each.value.ssh_algorithms_cipher
  ssh_algorithms_compression             = each.value.ssh_algorithms_compression
  ssh_algorithms_dh_group_min_size       = each.value.ssh_algorithms_dh_group_min_size
  ssh_algorithms_dh_group_preferred_size = each.value.ssh_algorithms_dh_group_preferred_size
  ssh_algorithms_dh_group_max_size       = each.value.ssh_algorithms_dh_group_max_size
  ned_keep_alive_interval                = each.value.ned_keep_alive_interval
  ned_keep_alive_count                   = each.value.ned_keep_alive_count
  connect_retries_attempts               = each.value.connect_retries_attempts
  connect_retries_timeout                = each.value.connect_retries_timeout
  trace                                  = each.value.trace
  trace_output                           = each.value.trace_output
  ned_settings_use_confirmed_commit      = each.value.ned_settings_use_confirmed_commit
  ned_settings_use_validate              = each.value.ned_settings_use_validate
  ned_settings_use_startup               = each.value.ned_settings_use_startup
  ned_settings_use_transaction_id        = each.value.ned_settings_use_transaction_id
  ned_settings_use_private_candidate     = each.value.ned_settings_use_private_candidate
  ned_settings_use_junos_rollback        = each.value.ned_settings_use_junos_rollback
  no_overwrite_enabled_by_default        = each.value.no_overwrite_enabled_by_default
  no_overwrite_compare                   = each.value.no_overwrite_compare
  lsa_no_overwrite_enabled_by_default    = each.value.lsa_no_overwrite_enabled_by_default
  lsa_no_overwrite_compare               = each.value.lsa_no_overwrite_compare
  out_of_sync_commit_behaviour           = each.value.out_of_sync_commit_behaviour
  use_lsa                                = each.value.use_lsa
  no_lsa                                 = each.value.no_lsa
  session_limits_max_sessions            = each.value.session_limits_max_sessions
  session_limits_connect_rate_burst      = each.value.session_limits_connect_rate_burst
  session_limits_max_wait_time           = each.value.session_limits_max_wait_time
  session_pool_max_sessions              = each.value.session_pool_max_sessions
  session_pool_idle_time                 = each.value.session_pool_idle_time
  session_pool_pool_max_sessions         = each.value.session_pool_pool_max_sessions
  commit_queue_enabled_by_default        = each.value.commit_queue_enabled_by_default
  commit_queue_atomic                    = each.value.commit_queue_atomic
  commit_queue_retry_attempts            = each.value.commit_queue_retry_attempts
  commit_queue_retry_timeout             = each.value.commit_queue_retry_timeout
  commit_queue_error_option              = each.value.commit_queue_error_option
  commit_retries_attempts                = each.value.commit_retries_attempts
  commit_retries_timeout                 = each.value.commit_retries_timeout
  trace_dir                              = each.value.trace_dir
  report_multiple_errors                 = each.value.report_multiple_errors
}
